services:
  server:
    build:
      context: .
      target: final
    ports:
      - '8080:8080'
    environment:
      - 'CUSTOMCONNSTR_POSTGRES=Host=postgres;Database=fish;Username=postgres;Password=postgres'
      - 'CUSTOMCONNSTR_REDISCACHE=redis:6379'
      - 'FISH_JWT__Key=2a8860a6ee5c004c583949072758c5c8ae9eadd8016b656c98194498ee4e963d'
      - 'FISH_JWT__Issuer=fish.alphabeta.pw'
      - 'FISH_JWT__Audience=fish.alphabeta.pw'
      - 'FISH_JWT__ExpiresInSecond=3600'
      - 'FISH_COOKIE__ExpireTimeSpan=00:30:00'
      - 'FISH_AUTHENTICATION__SCHEMES__BEARER__ValidAudiences=https://fish.alphabeta.pw'
      - 'FISH_AUTHENTICATION__SCHEMES__BEARER__ValidIssuer=dotnet-user-jwts'
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - pg_volume:/var/lib/postgresql/data

volumes:
  pg_volume: